module.exports = {
    model: { id: null, name: null, description: null, address: null, state: null, city: null, products: [] },
    schema: {
        fields: [
            {
                type: 'input',
                inputType: 'text',
                label: 'Nome',
                model: 'name',
                placeholder: 'Informe o nome da loja',
                required: true,
                validator: ['required'],
            },
            {
                type: 'textArea',
                label: 'Descrição',
                placeholder: 'Informe a descrição da loja',
                model: 'description',
                required: true,
                validator: ['required'],
            },
            {
                type: 'vueMultiSelect',
                label: 'Produtos',
                model: 'products',
                multiSelect: true,
                placeholder: 'Selecione os produtos desta loja',
                selectOptions: {
                    multiple: true,
                    trackBy: 'id',
                    label: 'name',
                    searchable: true,
                    taggable: true,
                    closeOnSelect: true,
                    hideSelected: true,
                },
                values: [],
                validator: ['required'],
            },
            {
                type: 'input',
                inputType: 'text',
                label: 'Endereço',
                model: 'address',
                placeholder: 'Informe o endereço da loja',
                required: true,
                validator: ['required'],
            },
            {
                type: 'vueMultiSelect',
                label: 'Estado',
                model: 'state',
                required: true,
                multiSelect: false,
                placeholder: 'Selecione um estado',
                selectOptions: {
                    multiple: false,
                    trackBy: 'id',
                    label: 'name',
                    searchable: true,
                    taggable: true,
                    closeOnSelect: true,
                    hideSelected: true,
                },
                values: [],
                validator: ['required'],
            },
            {
                type: 'vueMultiSelect',
                label: 'Cidade',
                model: 'city',
                required: true,
                multiSelect: false,
                placeholder: 'Selecione uma cidade',
                selectOptions: {
                    multiple: false,
                    trackBy: 'id',
                    label: 'name',
                    searchable: true,
                    taggable: true,
                    closeOnSelect: true,
                    hideSelected: true,
                },
                values: [],
                validator: ['required'],
            },
        ],
    },
    columns: [
        { key: 'name', label: 'Nome', filter: true },
        { key: 'address', label: 'Endereço', filter: true },
        { key: 'state', label: 'Estado', filter: true },
        { key: 'city', label: 'Cidade', filter: true },
        { key: 'created_at', label: 'Criado em', filter: true, dateMask: true },
    ],
    viewDataTypes: [
        { key: 'name', label: 'Nome' },
        { key: 'address', label: 'Endereço' },
        { key: 'state', label: 'Estado' },
        { key: 'city', label: 'Cidade' },
        { key: 'created_at', label: 'Criado em', dateMask: true },
        { key: 'products', label: 'Produtos', array: true, keys: [{ key: 'name', label: 'Nome' }, { key: 'description', label: 'Descrição' }] }
    ],
}